### ISSUE TITLE
help

### ISSUE THREAD

**Issue by orsx** [Teklad/tuxproc#1]
How I can include this on my project? I'm having problems with it.

Yes, I'm noob on linux.

**Comment by tekladis** [comment]
If you're using cmake and you don't have tuxproc installed on your system.  You'd place a copy of this in your project directory and use the following:
```cpp
find_package(TuxProc REQUIRED)
add_subdirectory(tuxproc/directory)
target_link_libraries(your_executable_name PRIVATE TuxProc::tuxproc)
```

If you decided to install it there are two ways.  First, with cmake (please ensure proper case usage):
```cpp
find_package(TuxProc REQUIRED)
target_link_libraries(TuxProc::TuxProc)
```

Or if you don't use cmake, there's the pkg-config way:
```cpp
pkg-config --libs tuxproc
pkg-config --cflags tuxproc
```

Inclusion in your source code should be done the following way:
```cpp
#include <tuxproc/process.h>
```

If you don't like any of these approaches you'd just throw all of the source files together (the .cpp/.h files) and compile them directly in your project.  In that case you'd include it in your source code depending on your directory structure.
