### ISSUE TITLE
reading csgo memory help please

### ISSUE THREAD

**Issue by ClearAsRain** [Teklad/tuxproc#2]
hi.I'm trying to use your class to read CSGO memory so I tried this:

```
#include <process.h>
#include <iostream>
#include <unistd.h>
int main()
{
    uintptr_t dwEntityList = 0x1ffa708;
    uintptr_t dwLocalPlayer = 0x1fcb5f0;
    uintptr_t m_iTeamNum = 0x128;
    uintptr_t m_iHealth = 0x134;
    uintptr_t incross = 0xBBD0;

    TuxProc::Process memory;
    uint32_t pid = memory.Attach("csgo_linux64");
    if(pid != 0)
    {
        while(!memory.GetRegion("client_panorama_client.so"))
        {
           memory.ParseMaps();
        }
            uintptr_t client = memory.GetRegion("client_panorama_client.so")->GetStartAddress();
            uintptr_t us = memory.GetCallAddress(client+dwLocalPlayer);
            uintptr_t ourhealth = memory.Read<uintptr_t>(us+m_iHealth);
            std::cout<<ourhealth<<std::endl;
    }
}
```

this give me 0.what did I do wrong ? 
sorry Im new to C++ and linux

**Comment by tekladis** [comment]
GetCallAddress is meant for if you're doing pattern scanning mostly.  You'll want to use Read for dwLocalPlayer as well.

**Comment by tekladis** [comment]
Also, health is of type int.  Using the correct type with the template prevents you from getting unexpected values.  With that said, here's what I'd do:

```cpp
auto localPlayer = memory.Read<uintptr_t>(client + dwLocalPlayer);
auto myHealth = memory.Read<int>(localPlayer + m_iHealth);
```

The type of your variable is explicitly set whenever you write out your template type, so this is a good use of auto.

For your netvars, the types tend to be indicated by the variable prefix in most cases.  Here's a real quick guide for the most common ones (ex. variable type: prefix) :
* **bool**: m_b
* **char**: m_ch
* **char array**: m_sz
* **float**: m_fl
* **int**: m_i, m_f
* **unsigned char**: m_uc, m_uch, m_ub
* **unsigned int**: m_n

Hope this was helpful.

**Comment by ClearAsRain** [comment]
thank you.it works now.
I thought GetCallAddress return pointer and Read, only return value.
thank you for your comment and your usefull program.
