### ISSUE TITLE
pattern scan & process memory regions failed implementation

### ISSUE THREAD

**Issue by sinitax** [Teklad/tuxproc#3]
I created a sample program and attempted to change the value of a cstring by modifying the processes memory remotely. 

The pattern scanner only detects the cstring when it is set to const, in which case modifying it remotely is impossible.

I confirmed that it is possible to modify the value remotely when not declared const, with a program which also uses process_vm_readv, with a pattern scan starting at rw enabled block of memory for the region of the programs name, which I found by dumping the contents of `/proc/<uid>/maps`

I assume this is a bug with the MapsParser not returning the full-valid range of memory?

**Comment by sinitax** [comment]
I think the problem is that Process::GetRegion only returns the first region with a matching name. The first region to be mapped in the maps file seems to be .text, which would explain why the pattern scan cant find non-const values.

**Comment by sinitax** [comment]
I decided to implement the changes myself on my fork of the repo.

When refactoring I addressed the aforementioned bug and the following issues:
https://stackoverflow.com/questions/29796264/is-there-still-a-use-for-inline
https://en.wikipedia.org/wiki/Hungarian_notation#Disadvantages

If you are interested, I can merge the changes.

**Comment by tekladis** [comment]
You can go ahead and make a PR for this.  I'll review the changes and see
about merging so long as there aren't any regressions. :)

**Comment by tekladis** [comment]
Merged... please feel free to update the README once more and provide updated usage examples when you have the time.  I'm fairly busy lately so any contributions are welcome.
